# Generated by Django 6.0.5 on 2026-07-31 05:15

import apps.search.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=42)),
                ('doc_id', models.PositiveIntegerField()),
                ('file_name', models.CharField(max_length=200)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('file', models.FileField(upload_to=apps.search.models.document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('session_key', 'doc_id'), name='unique_key')],
            },
        ),
    ]
