name: CMake Tests

on:
  push:
    branches: [main, wip]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake  libgtest-dev libmupdf-dev libfreetype6-dev libharfbuzz-dev libjpeg-dev libopenjp2-7-dev libjbig2dec0-dev zlib1g-dev libgumbo-dev libmujs-dev

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        working-directory: build
        run: ctest --verbose
